services:
    wordpress_db:
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=wordpressdb
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=wordpress
        volumes:
            - db_data:/var/lib/mysql
        image: mysql
    wordpress:
        environment:
            - WORDPRESS_DB_HOST=wordpress_db
            - WORDPRESS_DB_USER=wordpress
            - WORDPRESS_DB_PASSWORD=wordpress
            - WORDPRESS_DB_NAME=wordpressdb
        volumes:
            - wp-data:/var/www/html
        ports:
            - 80:80
        image: wordpress
volumes:
    db_data:
    wp-data:
